name: CI Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    # run build on latest ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        npm install
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: .        
  test:
    # run build on latest ubuntu
    runs-on: ubuntu-latest        
    needs: build
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
       name: build  
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x       
    - name: Test and Generate Coverage
      run: |
        npm run test 
