name: gke-run

on:
  push:
    branches:
      - master
      - main
env:
  run_unit_test: main

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        npm install
    - name: Test and Generate Coverage
      if: ${{ env.run_unit_test == 'dev' }}
      run: |
        npm run coverage  
