name: node-docker

on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    container: 
      image: node:14-alpine
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        npm install
    - name: Test and Generate Coverage
      run: |
        npm run coverage  
